docs:
  - text: Installing & Upgrading
    link: install.html
    children:
      - text: Installing from Light Table
        link: install-manual.html
      - text: Offline / Behind a Firewall
        link: offline.html
      - text: Troubleshooting
        link: troubleshooting.html
  - text: Evaluation & Display
    link: evaluation.html
  - text: Developing Modules and Packages
    link: modules.html
  - text: Connecting to the Terminal and IJulia
    link: terminal.html
  - text: Settings & Configuration
    link: settings.html
  - text: Other features and notes
    link: notes.html
  - text: Light Table Notes
    link: ltnotes.html
  - text: Community & Help
    link: /community/

navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Docs
    url: /docs/
  - text: Community
    url: /community/
  - text: Discuss
    url: http://discuss.junolab.org/
